"""table modifci  outbound transactions

Revision ID: 21869f9887d4
Revises: 58a00e014355
Create Date: 2024-06-30 16:04:20.209257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21869f9887d4'
down_revision = '58a00e014355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.alter_column('truck_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.alter_column('truck_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
