"""changes in outbound table

Revision ID: 299c8905e4a7
Revises: 553b72d0fa6c
Create Date: 2024-06-22 14:14:49.773867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '299c8905e4a7'
down_revision = '553b72d0fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_records',
    sa.Column('outbound_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_in_tons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_proof', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('outbound_id')
    )
    op.drop_table('outbound')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound',
    sa.Column('outbound_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('truck_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('weight_in_tons', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('receipt_proof', sa.BLOB(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('update_date', mysql.DATETIME(), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('outbound_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('outbound_records')
    # ### end Alembic commands ###
