"""new table for outbound transactions

Revision ID: 553b72d0fa6c
Revises: 2512a00fa4e1
Create Date: 2024-06-22 13:30:51.939173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553b72d0fa6c'
down_revision = '2512a00fa4e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound',
    sa.Column('outbound_id', sa.Integer(), nullable=False),
    sa.Column('truck_number', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_in_tons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_proof', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('outbound_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbound')
    # ### end Alembic commands ###
