"""changes in outbound table

Revision ID: 58a00e014355
Revises: b5e569f584be
Create Date: 2024-06-22 15:22:32.380342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a00e014355'
down_revision = 'b5e569f584be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('truck_date', sa.Date(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=False))
        batch_op.drop_column('truck_date')

    # ### end Alembic commands ###
