"""changes in outbound table

Revision ID: b5e569f584be
Revises: 299c8905e4a7
Create Date: 2024-06-22 15:19:14.321157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5e569f584be'
down_revision = '299c8905e4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.alter_column('receipt_proof',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_records', schema=None) as batch_op:
        batch_op.alter_column('receipt_proof',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               nullable=False)

    # ### end Alembic commands ###
